// Scala case class + Circe codec generator from a JSON value
// Heuristics: single sample inference, simple plural -> singular for array element classes, camelCase class names.

export function generateScala(value: any, rootName = 'ParsedJson'): string { // eslint-disable-line @typescript-eslint/no-explicit-any
  const defs: Record<string, ClassDef> = {};
  const usedNames = new Set<string>();

  function capitalize(name: string): string {
    return name.charAt(0).toUpperCase() + name.slice(1);
  }
  function toCamel(name: string): string {
    return name
      .replace(/[^A-Za-z0-9_]+/g, ' ') // separators
      .split(/\s+/)
      .filter(Boolean)
      .map((p, i) => i === 0 ? p.charAt(0).toUpperCase() + p.slice(1) : capitalize(p.toLowerCase()))
      .join('');
  }
  function unique(name: string): string {
    let n = name;
    let i = 2;
    while (usedNames.has(n)) { n = name + i; i++; }
    usedNames.add(n);
    return n;
  }

  interface ClassField { name: string; tpe: string; original: string }
  interface ClassDef { name: string; fields: ClassField[] }

  function inferType(key: string, v: any, parentClass: string): string { // eslint-disable-line @typescript-eslint/no-explicit-any
    if (v === null) return 'Option[Json]';
    const t = typeof v;
    if (t === 'string') return 'String';
    if (t === 'number') return Number.isInteger(v) ? 'Int' : 'Double';
    if (t === 'boolean') return 'Boolean';
    if (Array.isArray(v)) {
      if (!v.length) return 'List[Json]';
      // unify element types
      const elemTypes = Array.from(new Set(v.map(e => inferType(singularize(key), e, parentClass))));
      if (elemTypes.length === 1) return `List[${elemTypes[0]}]`;
      return 'List[Json]';
    }
    if (t === 'object') {
      const className = registerClass(deriveClassName(key, parentClass), v as Record<string, any>); // eslint-disable-line @typescript-eslint/no-explicit-any
      return className;
    }
    return 'Json';
  }

  function singularize(name: string): string {
    if (name.endsWith('ies')) return name.slice(0, -3) + 'y';
    if (name.endsWith('ses')) return name.slice(0, -2);
    if (name.endsWith('s') && name.length > 1) return name.slice(0, -1);
    return name;
  }

  function deriveClassName(key: string, parent: string): string {
    if (!key) return parent + 'Item';
    const c = toCamel(singularize(key));
    return c || parent + 'Item';
  }

  function sanitizeField(name: string): string {
    if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) return name;
    // fallback convert invalid chars to _ and ensure not starting with digit
    let n = name.replace(/[^A-Za-z0-9_]/g, '_');
    if (/^[0-9]/.test(n)) n = '_' + n;
    return n;
  }

  function registerClass(name: string, obj: Record<string, any>): string { // eslint-disable-line @typescript-eslint/no-explicit-any
    const finalName = unique(capitalize(name));
    const fields: ClassField[] = Object.keys(obj).sort().map(k => {
      const fieldName = sanitizeField(k);
      const tpe = inferType(k, (obj as any)[k], finalName); // eslint-disable-line @typescript-eslint/no-explicit-any
      return { name: fieldName, tpe, original: k };
    });
    defs[finalName] = { name: finalName, fields };
    return finalName;
  }

  // Kickoff depending on root shape (object roots become ParsedJson directly)
  let rootType: string;
  let wrapperNeeded = false;
  if (value && typeof value === 'object' && !Array.isArray(value)) {
    rootType = registerClass(rootName, value as Record<string, any>); // eslint-disable-line @typescript-eslint/no-explicit-any
  } else {
    // derive underlying type then wrap
    if (Array.isArray(value)) {
      if (value.length && typeof value[0] === 'object' && value[0] !== null && !Array.isArray(value[0])) {
        const elemName = singularize(rootName + 'Item');
        const cn = registerClass(elemName, value[0] as Record<string, any>); // eslint-disable-line @typescript-eslint/no-explicit-any
        rootType = `List[${cn}]`;
      } else {
        const elemTypes = Array.from(new Set(value.map(v => inferType('Item', v, rootName))));
        rootType = elemTypes.length === 1 ? `List[${elemTypes[0]}]` : 'List[Json]';
      }
    } else {
      rootType = inferType(rootName, value, '');
    }
    wrapperNeeded = true;
  }

  const needJsonImport = Object.values(defs).some(d => d.fields.some(f => /Json\b/.test(f.tpe))) || /Json\b/.test(rootType);

  // Order: dependencies first (naive: just sort by name except root last if case class)
  const classOrder = Object.keys(defs).sort((a,b)=> a.localeCompare(b));

  const lines: string[] = [];
  lines.push('// Generated by json-beautify Scala generator');
  lines.push('import io.circe._');
  lines.push('import io.circe.JsonObject');
  if (needJsonImport) lines.push('import io.circe.Json');
  lines.push('import io.circe.syntax._');
  lines.push('import io.circe.generic.semiauto._');
  lines.push('');

  classOrder.forEach(cn => {
    const c = defs[cn];
    if (c.name === rootName && !wrapperNeeded) {
      // Root case class already named ParsedJson
      const body = c.fields.map(f => `${f.name}: ${f.tpe}`).join(', ');
      lines.push(`case class ${c.name}(${body})`);
    } else if (c.name !== rootName) {
      const body = c.fields.map(f => `${f.name}: ${f.tpe}`).join(', ');
      lines.push(`case class ${c.name}(${body})`);
    }
  });
  if (wrapperNeeded) {
    lines.push(`case class ${rootName}(value: ${rootType})`);
  }
  if (classOrder.length) lines.push('');
  // Root alias no longer needed; we always produce ParsedJson case class
  // Codecs
  classOrder.forEach(cn => {
    if (cn !== rootName) {
      lines.push(`implicit val ${lowerFirst(cn)}Decoder: Decoder[${cn}] = deriveDecoder[${cn}]`);
      lines.push(`implicit val ${lowerFirst(cn)}Encoder: Encoder.AsObject[${cn}] = deriveEncoder[${cn}]`);
      lines.push('');
    } else if (!wrapperNeeded) {
      lines.push(`implicit val ${lowerFirst(cn)}Decoder: Decoder[${cn}] = deriveDecoder[${cn}]`);
      lines.push(`implicit val ${lowerFirst(cn)}Encoder: Encoder.AsObject[${cn}] = deriveEncoder[${cn}]`);
      lines.push('');
    }
  });
  if (wrapperNeeded) {
    lines.push(`implicit val parsedJsonDecoder: Decoder[${rootName}] = Decoder.instance(c => c.as[${rootType}].map(${rootName}.apply))`);
    lines.push(`implicit val parsedJsonEncoder: Encoder.AsObject[${rootName}] = Encoder.instance(p => p.value.asJson.asObject.getOrElse(JsonObject.empty))`);
    lines.push('');
  }
  // Convenience parse & stringify
  lines.push(`object ${rootName}Json {`);
  lines.push(`  def parse(json: String)(implicit d: Decoder[${rootName}]): Either[Error, ${rootName}] = io.circe.parser.decode[${rootName}](json)`);
  lines.push(`  implicit class ${rootName}Ops(val underlying: ${rootName}) extends AnyVal { def asJsonString(implicit e: Encoder[${rootName}]): String = underlying.asJson.spaces2 }`);
  lines.push('}');

  return lines.join('\n');
}

function lowerFirst(s: string): string { return s.charAt(0).toLowerCase() + s.slice(1); }
